language: "en"

pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: "CountVectorsFeaturizer"
- name: "DIETClassifier"
# - name: DucklingEntityExtractor
#   url: http://localhost:7000
#   dimensions:
#     - number

policies:
- name: MemoizationPolicy
- name: TEDPolicy
- name: RulePolicy

assistant_id: 20231121-012112-deafening-snare
